# Generated by Django 5.2.15 on 2026-06-06 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, max_length=250, verbose_name='Descripción corta (para cards)')),
                ('is_featured', models.BooleanField(default=False, help_text='Solo un proyecto debe ser destacado a la vez', verbose_name='Proyecto destacado')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/', verbose_name='Imagen de portada')),
                ('users_count', models.PositiveIntegerField(default=0, help_text='Número aproximado de usuarios', verbose_name='Usuarios activos')),
                ('duration_months', models.PositiveSmallIntegerField(default=0, verbose_name='Duración (meses)')),
                ('url_live', models.URLField(blank=True, verbose_name='URL en producción')),
                ('url_repo', models.URLField(blank=True, verbose_name='URL repositorio')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('development', 'En desarrollo'), ('archived', 'Archivado')], default='active', max_length=20, verbose_name='Estado')),
                ('carousel_order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden en carrusel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-is_featured', 'carousel_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Tecnología')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Clase CSS del ícono (devicons, simple-icons, etc.)', max_length=100)),
                ('color', models.CharField(default='#D4AF37', help_text='Color hexadecimal para el badge', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen del proyecto',
                'verbose_name_plural': 'Imágenes del proyecto',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='projects.technology', verbose_name='Tecnologías'),
        ),
    ]
