# Generated by Django 5.2.15 on 2026-06-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industria')),
                ('company_size', models.CharField(blank=True, max_length=100, verbose_name='Tamaño de empresa')),
                ('problem', models.TextField(verbose_name='Problema')),
                ('solution', models.TextField(verbose_name='Solución')),
                ('result', models.TextField(verbose_name='Resultado')),
                ('metric_1_label', models.CharField(blank=True, max_length=80)),
                ('metric_1_value', models.CharField(blank=True, max_length=80)),
                ('metric_2_label', models.CharField(blank=True, max_length=80)),
                ('metric_2_value', models.CharField(blank=True, max_length=80)),
                ('metric_3_label', models.CharField(blank=True, max_length=80)),
                ('metric_3_value', models.CharField(blank=True, max_length=80)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caso de éxito',
                'verbose_name_plural': 'Casos de éxito',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
